// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rossmerr/couchdb_go/models"
)

// ClusterSetupPostReader is a Reader for the ClusterSetupPost structure.
type ClusterSetupPostReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ClusterSetupPostReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewClusterSetupPostOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewClusterSetupPostCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewClusterSetupPostBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewClusterSetupPostInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewClusterSetupPostOK creates a ClusterSetupPostOK with default headers values
func NewClusterSetupPostOK() *ClusterSetupPostOK {
	return &ClusterSetupPostOK{}
}

/* ClusterSetupPostOK describes a response with status code 200, with default header values.

Request completed successfully
*/
type ClusterSetupPostOK struct {
	Payload *models.OK
}

func (o *ClusterSetupPostOK) Error() string {
	return fmt.Sprintf("[POST /_cluster_setup][%d] clusterSetupPostOK  %+v", 200, o.Payload)
}
func (o *ClusterSetupPostOK) GetPayload() *models.OK {
	return o.Payload
}

func (o *ClusterSetupPostOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OK)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewClusterSetupPostCreated creates a ClusterSetupPostCreated with default headers values
func NewClusterSetupPostCreated() *ClusterSetupPostCreated {
	return &ClusterSetupPostCreated{}
}

/* ClusterSetupPostCreated describes a response with status code 201, with default header values.

Request completed successfully
*/
type ClusterSetupPostCreated struct {
	Payload *models.OK
}

func (o *ClusterSetupPostCreated) Error() string {
	return fmt.Sprintf("[POST /_cluster_setup][%d] clusterSetupPostCreated  %+v", 201, o.Payload)
}
func (o *ClusterSetupPostCreated) GetPayload() *models.OK {
	return o.Payload
}

func (o *ClusterSetupPostCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OK)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewClusterSetupPostBadRequest creates a ClusterSetupPostBadRequest with default headers values
func NewClusterSetupPostBadRequest() *ClusterSetupPostBadRequest {
	return &ClusterSetupPostBadRequest{}
}

/* ClusterSetupPostBadRequest describes a response with status code 400, with default header values.

Failed
*/
type ClusterSetupPostBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *ClusterSetupPostBadRequest) Error() string {
	return fmt.Sprintf("[POST /_cluster_setup][%d] clusterSetupPostBadRequest  %+v", 400, o.Payload)
}
func (o *ClusterSetupPostBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ClusterSetupPostBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewClusterSetupPostInternalServerError creates a ClusterSetupPostInternalServerError with default headers values
func NewClusterSetupPostInternalServerError() *ClusterSetupPostInternalServerError {
	return &ClusterSetupPostInternalServerError{}
}

/* ClusterSetupPostInternalServerError describes a response with status code 500, with default header values.

JSON specification was invalid
*/
type ClusterSetupPostInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *ClusterSetupPostInternalServerError) Error() string {
	return fmt.Sprintf("[POST /_cluster_setup][%d] clusterSetupPostInternalServerError  %+v", 500, o.Payload)
}
func (o *ClusterSetupPostInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ClusterSetupPostInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
