// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSearchAnalyzeParams creates a new SearchAnalyzeParams object
// with the default values initialized.
func NewSearchAnalyzeParams() *SearchAnalyzeParams {
	var ()
	return &SearchAnalyzeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSearchAnalyzeParamsWithTimeout creates a new SearchAnalyzeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSearchAnalyzeParamsWithTimeout(timeout time.Duration) *SearchAnalyzeParams {
	var ()
	return &SearchAnalyzeParams{

		timeout: timeout,
	}
}

// NewSearchAnalyzeParamsWithContext creates a new SearchAnalyzeParams object
// with the default values initialized, and the ability to set a context for a request
func NewSearchAnalyzeParamsWithContext(ctx context.Context) *SearchAnalyzeParams {
	var ()
	return &SearchAnalyzeParams{

		Context: ctx,
	}
}

// NewSearchAnalyzeParamsWithHTTPClient creates a new SearchAnalyzeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSearchAnalyzeParamsWithHTTPClient(client *http.Client) *SearchAnalyzeParams {
	var ()
	return &SearchAnalyzeParams{
		HTTPClient: client,
	}
}

/*SearchAnalyzeParams contains all the parameters to send to the API endpoint
for the search analyze operation typically these are written to a http.Request
*/
type SearchAnalyzeParams struct {

	/*Body*/
	Body SearchAnalyzeBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the search analyze params
func (o *SearchAnalyzeParams) WithTimeout(timeout time.Duration) *SearchAnalyzeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search analyze params
func (o *SearchAnalyzeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search analyze params
func (o *SearchAnalyzeParams) WithContext(ctx context.Context) *SearchAnalyzeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search analyze params
func (o *SearchAnalyzeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search analyze params
func (o *SearchAnalyzeParams) WithHTTPClient(client *http.Client) *SearchAnalyzeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search analyze params
func (o *SearchAnalyzeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the search analyze params
func (o *SearchAnalyzeParams) WithBody(body SearchAnalyzeBody) *SearchAnalyzeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the search analyze params
func (o *SearchAnalyzeParams) SetBody(body SearchAnalyzeBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SearchAnalyzeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
