// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewServerActiveTasksParams creates a new ServerActiveTasksParams object
// with the default values initialized.
func NewServerActiveTasksParams() *ServerActiveTasksParams {

	return &ServerActiveTasksParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewServerActiveTasksParamsWithTimeout creates a new ServerActiveTasksParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewServerActiveTasksParamsWithTimeout(timeout time.Duration) *ServerActiveTasksParams {

	return &ServerActiveTasksParams{

		timeout: timeout,
	}
}

// NewServerActiveTasksParamsWithContext creates a new ServerActiveTasksParams object
// with the default values initialized, and the ability to set a context for a request
func NewServerActiveTasksParamsWithContext(ctx context.Context) *ServerActiveTasksParams {

	return &ServerActiveTasksParams{

		Context: ctx,
	}
}

// NewServerActiveTasksParamsWithHTTPClient creates a new ServerActiveTasksParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewServerActiveTasksParamsWithHTTPClient(client *http.Client) *ServerActiveTasksParams {

	return &ServerActiveTasksParams{
		HTTPClient: client,
	}
}

/*ServerActiveTasksParams contains all the parameters to send to the API endpoint
for the server active tasks operation typically these are written to a http.Request
*/
type ServerActiveTasksParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the server active tasks params
func (o *ServerActiveTasksParams) WithTimeout(timeout time.Duration) *ServerActiveTasksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the server active tasks params
func (o *ServerActiveTasksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the server active tasks params
func (o *ServerActiveTasksParams) WithContext(ctx context.Context) *ServerActiveTasksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the server active tasks params
func (o *ServerActiveTasksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the server active tasks params
func (o *ServerActiveTasksParams) WithHTTPClient(client *http.Client) *ServerActiveTasksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the server active tasks params
func (o *ServerActiveTasksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ServerActiveTasksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
