// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ServerClusterSetupReader is a Reader for the ServerClusterSetup structure.
type ServerClusterSetupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServerClusterSetupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewServerClusterSetupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewServerClusterSetupOK creates a ServerClusterSetupOK with default headers values
func NewServerClusterSetupOK() *ServerClusterSetupOK {
	return &ServerClusterSetupOK{}
}

/*ServerClusterSetupOK handles this case with default header values.

Request completed successfully
*/
type ServerClusterSetupOK struct {
	Payload *ServerClusterSetupOKBody
}

func (o *ServerClusterSetupOK) Error() string {
	return fmt.Sprintf("[GET /_cluster_setup][%d] serverClusterSetupOK  %+v", 200, o.Payload)
}

func (o *ServerClusterSetupOK) GetPayload() *ServerClusterSetupOKBody {
	return o.Payload
}

func (o *ServerClusterSetupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ServerClusterSetupOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ServerClusterSetupOKBody server cluster setup o k body
swagger:model ServerClusterSetupOKBody
*/
type ServerClusterSetupOKBody struct {

	// Current state of the node and/or cluster (see below)
	// Enum: [cluster_disabled single_node_disabled single_node_enabled cluster_enabled cluster_finished]
	State string `json:"state,omitempty"`
}

// Validate validates this server cluster setup o k body
func (o *ServerClusterSetupOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateState(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var serverClusterSetupOKBodyTypeStatePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["cluster_disabled","single_node_disabled","single_node_enabled","cluster_enabled","cluster_finished"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		serverClusterSetupOKBodyTypeStatePropEnum = append(serverClusterSetupOKBodyTypeStatePropEnum, v)
	}
}

const (

	// ServerClusterSetupOKBodyStateClusterDisabled captures enum value "cluster_disabled"
	ServerClusterSetupOKBodyStateClusterDisabled string = "cluster_disabled"

	// ServerClusterSetupOKBodyStateSingleNodeDisabled captures enum value "single_node_disabled"
	ServerClusterSetupOKBodyStateSingleNodeDisabled string = "single_node_disabled"

	// ServerClusterSetupOKBodyStateSingleNodeEnabled captures enum value "single_node_enabled"
	ServerClusterSetupOKBodyStateSingleNodeEnabled string = "single_node_enabled"

	// ServerClusterSetupOKBodyStateClusterEnabled captures enum value "cluster_enabled"
	ServerClusterSetupOKBodyStateClusterEnabled string = "cluster_enabled"

	// ServerClusterSetupOKBodyStateClusterFinished captures enum value "cluster_finished"
	ServerClusterSetupOKBodyStateClusterFinished string = "cluster_finished"
)

// prop value enum
func (o *ServerClusterSetupOKBody) validateStateEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, serverClusterSetupOKBodyTypeStatePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *ServerClusterSetupOKBody) validateState(formats strfmt.Registry) error {

	if swag.IsZero(o.State) { // not required
		return nil
	}

	// value enum
	if err := o.validateStateEnum("serverClusterSetupOK"+"."+"state", "body", o.State); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ServerClusterSetupOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ServerClusterSetupOKBody) UnmarshalBinary(b []byte) error {
	var res ServerClusterSetupOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
