// Code generated by go-swagger; DO NOT EDIT.

package database

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewBulkGetParams creates a new BulkGetParams object
// with the default values initialized.
func NewBulkGetParams() *BulkGetParams {
	var ()
	return &BulkGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewBulkGetParamsWithTimeout creates a new BulkGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewBulkGetParamsWithTimeout(timeout time.Duration) *BulkGetParams {
	var ()
	return &BulkGetParams{

		timeout: timeout,
	}
}

// NewBulkGetParamsWithContext creates a new BulkGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewBulkGetParamsWithContext(ctx context.Context) *BulkGetParams {
	var ()
	return &BulkGetParams{

		Context: ctx,
	}
}

// NewBulkGetParamsWithHTTPClient creates a new BulkGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewBulkGetParamsWithHTTPClient(client *http.Client) *BulkGetParams {
	var ()
	return &BulkGetParams{
		HTTPClient: client,
	}
}

/*BulkGetParams contains all the parameters to send to the API endpoint
for the bulk get operation typically these are written to a http.Request
*/
type BulkGetParams struct {

	/*Body
	  List of document objects, with id, and optionally rev and atts_since

	*/
	Body BulkGetBody
	/*Db
	  Database name

	*/
	Db string
	/*Revs
	  Give the revisions history

	*/
	Revs *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the bulk get params
func (o *BulkGetParams) WithTimeout(timeout time.Duration) *BulkGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the bulk get params
func (o *BulkGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the bulk get params
func (o *BulkGetParams) WithContext(ctx context.Context) *BulkGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the bulk get params
func (o *BulkGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the bulk get params
func (o *BulkGetParams) WithHTTPClient(client *http.Client) *BulkGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the bulk get params
func (o *BulkGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the bulk get params
func (o *BulkGetParams) WithBody(body BulkGetBody) *BulkGetParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the bulk get params
func (o *BulkGetParams) SetBody(body BulkGetBody) {
	o.Body = body
}

// WithDb adds the db to the bulk get params
func (o *BulkGetParams) WithDb(db string) *BulkGetParams {
	o.SetDb(db)
	return o
}

// SetDb adds the db to the bulk get params
func (o *BulkGetParams) SetDb(db string) {
	o.Db = db
}

// WithRevs adds the revs to the bulk get params
func (o *BulkGetParams) WithRevs(revs *bool) *BulkGetParams {
	o.SetRevs(revs)
	return o
}

// SetRevs adds the revs to the bulk get params
func (o *BulkGetParams) SetRevs(revs *bool) {
	o.Revs = revs
}

// WriteToRequest writes these params to a swagger request
func (o *BulkGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param db
	if err := r.SetPathParam("db", o.Db); err != nil {
		return err
	}

	if o.Revs != nil {

		// query param revs
		var qrRevs bool
		if o.Revs != nil {
			qrRevs = *o.Revs
		}
		qRevs := swag.FormatBool(qrRevs)
		if qRevs != "" {
			if err := r.SetQueryParam("revs", qRevs); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
