// Code generated by go-swagger; DO NOT EDIT.

package database

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDbDeleteParams creates a new DbDeleteParams object
// with the default values initialized.
func NewDbDeleteParams() *DbDeleteParams {
	var ()
	return &DbDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDbDeleteParamsWithTimeout creates a new DbDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDbDeleteParamsWithTimeout(timeout time.Duration) *DbDeleteParams {
	var ()
	return &DbDeleteParams{

		timeout: timeout,
	}
}

// NewDbDeleteParamsWithContext creates a new DbDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewDbDeleteParamsWithContext(ctx context.Context) *DbDeleteParams {
	var ()
	return &DbDeleteParams{

		Context: ctx,
	}
}

// NewDbDeleteParamsWithHTTPClient creates a new DbDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDbDeleteParamsWithHTTPClient(client *http.Client) *DbDeleteParams {
	var ()
	return &DbDeleteParams{
		HTTPClient: client,
	}
}

/*DbDeleteParams contains all the parameters to send to the API endpoint
for the db delete operation typically these are written to a http.Request
*/
type DbDeleteParams struct {

	/*Db
	  Database name

	*/
	Db string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the db delete params
func (o *DbDeleteParams) WithTimeout(timeout time.Duration) *DbDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the db delete params
func (o *DbDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the db delete params
func (o *DbDeleteParams) WithContext(ctx context.Context) *DbDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the db delete params
func (o *DbDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the db delete params
func (o *DbDeleteParams) WithHTTPClient(client *http.Client) *DbDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the db delete params
func (o *DbDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDb adds the db to the db delete params
func (o *DbDeleteParams) WithDb(db string) *DbDeleteParams {
	o.SetDb(db)
	return o
}

// SetDb adds the db to the db delete params
func (o *DbDeleteParams) SetDb(db string) {
	o.Db = db
}

// WriteToRequest writes these params to a swagger request
func (o *DbDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param db
	if err := r.SetPathParam("db", o.Db); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
