// Code generated by go-swagger; DO NOT EDIT.

package database

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rossmerr/couchdb_go/models"
)

// DbSecurityGetReader is a Reader for the DbSecurityGet structure.
type DbSecurityGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DbSecurityGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDbSecurityGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDbSecurityGetOK creates a DbSecurityGetOK with default headers values
func NewDbSecurityGetOK() *DbSecurityGetOK {
	return &DbSecurityGetOK{}
}

/* DbSecurityGetOK describes a response with status code 200, with default header values.

Request completed successfully
*/
type DbSecurityGetOK struct {
	Payload *models.InlineResponse2005
}

func (o *DbSecurityGetOK) Error() string {
	return fmt.Sprintf("[GET /{db}/_security][%d] dbSecurityGetOK  %+v", 200, o.Payload)
}
func (o *DbSecurityGetOK) GetPayload() *models.InlineResponse2005 {
	return o.Payload
}

func (o *DbSecurityGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InlineResponse2005)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
