// Code generated by go-swagger; DO NOT EDIT.

package database

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewExistsParams creates a new ExistsParams object
// with the default values initialized.
func NewExistsParams() *ExistsParams {
	var ()
	return &ExistsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewExistsParamsWithTimeout creates a new ExistsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewExistsParamsWithTimeout(timeout time.Duration) *ExistsParams {
	var ()
	return &ExistsParams{

		timeout: timeout,
	}
}

// NewExistsParamsWithContext creates a new ExistsParams object
// with the default values initialized, and the ability to set a context for a request
func NewExistsParamsWithContext(ctx context.Context) *ExistsParams {
	var ()
	return &ExistsParams{

		Context: ctx,
	}
}

// NewExistsParamsWithHTTPClient creates a new ExistsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewExistsParamsWithHTTPClient(client *http.Client) *ExistsParams {
	var ()
	return &ExistsParams{
		HTTPClient: client,
	}
}

/*ExistsParams contains all the parameters to send to the API endpoint
for the exists operation typically these are written to a http.Request
*/
type ExistsParams struct {

	/*Db
	  Database name

	*/
	Db string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the exists params
func (o *ExistsParams) WithTimeout(timeout time.Duration) *ExistsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the exists params
func (o *ExistsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the exists params
func (o *ExistsParams) WithContext(ctx context.Context) *ExistsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the exists params
func (o *ExistsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the exists params
func (o *ExistsParams) WithHTTPClient(client *http.Client) *ExistsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the exists params
func (o *ExistsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDb adds the db to the exists params
func (o *ExistsParams) WithDb(db string) *ExistsParams {
	o.SetDb(db)
	return o
}

// SetDb adds the db to the exists params
func (o *ExistsParams) SetDb(db string) {
	o.Db = db
}

// WriteToRequest writes these params to a swagger request
func (o *ExistsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param db
	if err := r.SetPathParam("db", o.Db); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
