// Code generated by go-swagger; DO NOT EDIT.

package database

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSecurityGetParams creates a new SecurityGetParams object
// with the default values initialized.
func NewSecurityGetParams() *SecurityGetParams {
	var ()
	return &SecurityGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSecurityGetParamsWithTimeout creates a new SecurityGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSecurityGetParamsWithTimeout(timeout time.Duration) *SecurityGetParams {
	var ()
	return &SecurityGetParams{

		timeout: timeout,
	}
}

// NewSecurityGetParamsWithContext creates a new SecurityGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewSecurityGetParamsWithContext(ctx context.Context) *SecurityGetParams {
	var ()
	return &SecurityGetParams{

		Context: ctx,
	}
}

// NewSecurityGetParamsWithHTTPClient creates a new SecurityGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSecurityGetParamsWithHTTPClient(client *http.Client) *SecurityGetParams {
	var ()
	return &SecurityGetParams{
		HTTPClient: client,
	}
}

/*SecurityGetParams contains all the parameters to send to the API endpoint
for the security get operation typically these are written to a http.Request
*/
type SecurityGetParams struct {

	/*Db
	  Database name

	*/
	Db string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the security get params
func (o *SecurityGetParams) WithTimeout(timeout time.Duration) *SecurityGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the security get params
func (o *SecurityGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the security get params
func (o *SecurityGetParams) WithContext(ctx context.Context) *SecurityGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the security get params
func (o *SecurityGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the security get params
func (o *SecurityGetParams) WithHTTPClient(client *http.Client) *SecurityGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the security get params
func (o *SecurityGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDb adds the db to the security get params
func (o *SecurityGetParams) WithDb(db string) *SecurityGetParams {
	o.SetDb(db)
	return o
}

// SetDb adds the db to the security get params
func (o *SecurityGetParams) SetDb(db string) {
	o.Db = db
}

// WriteToRequest writes these params to a swagger request
func (o *SecurityGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param db
	if err := r.SetPathParam("db", o.Db); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
