// Code generated by go-swagger; DO NOT EDIT.

package design_documents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDesignDocInfoParams creates a new DesignDocInfoParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDesignDocInfoParams() *DesignDocInfoParams {
	return &DesignDocInfoParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDesignDocInfoParamsWithTimeout creates a new DesignDocInfoParams object
// with the ability to set a timeout on a request.
func NewDesignDocInfoParamsWithTimeout(timeout time.Duration) *DesignDocInfoParams {
	return &DesignDocInfoParams{
		timeout: timeout,
	}
}

// NewDesignDocInfoParamsWithContext creates a new DesignDocInfoParams object
// with the ability to set a context for a request.
func NewDesignDocInfoParamsWithContext(ctx context.Context) *DesignDocInfoParams {
	return &DesignDocInfoParams{
		Context: ctx,
	}
}

// NewDesignDocInfoParamsWithHTTPClient creates a new DesignDocInfoParams object
// with the ability to set a custom HTTPClient for a request.
func NewDesignDocInfoParamsWithHTTPClient(client *http.Client) *DesignDocInfoParams {
	return &DesignDocInfoParams{
		HTTPClient: client,
	}
}

/* DesignDocInfoParams contains all the parameters to send to the API endpoint
   for the design doc info operation.

   Typically these are written to a http.Request.
*/
type DesignDocInfoParams struct {

	/* Db.

	   Database name
	*/
	Db string

	/* Ddoc.

	   Design document id
	*/
	Ddoc string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the design doc info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DesignDocInfoParams) WithDefaults() *DesignDocInfoParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the design doc info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DesignDocInfoParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the design doc info params
func (o *DesignDocInfoParams) WithTimeout(timeout time.Duration) *DesignDocInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the design doc info params
func (o *DesignDocInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the design doc info params
func (o *DesignDocInfoParams) WithContext(ctx context.Context) *DesignDocInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the design doc info params
func (o *DesignDocInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the design doc info params
func (o *DesignDocInfoParams) WithHTTPClient(client *http.Client) *DesignDocInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the design doc info params
func (o *DesignDocInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDb adds the db to the design doc info params
func (o *DesignDocInfoParams) WithDb(db string) *DesignDocInfoParams {
	o.SetDb(db)
	return o
}

// SetDb adds the db to the design doc info params
func (o *DesignDocInfoParams) SetDb(db string) {
	o.Db = db
}

// WithDdoc adds the ddoc to the design doc info params
func (o *DesignDocInfoParams) WithDdoc(ddoc string) *DesignDocInfoParams {
	o.SetDdoc(ddoc)
	return o
}

// SetDdoc adds the ddoc to the design doc info params
func (o *DesignDocInfoParams) SetDdoc(ddoc string) {
	o.Ddoc = ddoc
}

// WriteToRequest writes these params to a swagger request
func (o *DesignDocInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param db
	if err := r.SetPathParam("db", o.Db); err != nil {
		return err
	}

	// path param ddoc
	if err := r.SetPathParam("ddoc", o.Ddoc); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
