// Code generated by go-swagger; DO NOT EDIT.

package design_documents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new design documents API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for design documents API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	DesignDocDelete(params *DesignDocDeleteParams) (*DesignDocDeleteOK, *DesignDocDeleteAccepted, error)

	DesignDocExists(params *DesignDocExistsParams) (*DesignDocExistsOK, error)

	DesignDocGet(params *DesignDocGetParams) (*DesignDocGetOK, error)

	DesignDocInfo(params *DesignDocInfoParams) (*DesignDocInfoOK, error)

	DesignDocPut(params *DesignDocPutParams) (*DesignDocPutOK, error)

	DesignDocSearch(params *DesignDocSearchParams) (*DesignDocSearchOK, error)

	DesignDocSearchInfo(params *DesignDocSearchInfoParams) (*DesignDocSearchInfoOK, error)

	DesignDocView(params *DesignDocViewParams) (*DesignDocViewOK, error)

	DesignDocViewPost(params *DesignDocViewPostParams) (*DesignDocViewPostOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  DesignDocDelete deletes the specified document from the database you must supply the current latest revision either by using the rev parameter to specify the revision
*/
func (a *Client) DesignDocDelete(params *DesignDocDeleteParams) (*DesignDocDeleteOK, *DesignDocDeleteAccepted, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDesignDocDeleteParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "designDocDelete",
		Method:             "DELETE",
		PathPattern:        "/{db}/_design/{ddoc}",
		ProducesMediaTypes: []string{"application/json", "text/plain"},
		ConsumesMediaTypes: []string{"application/json", "text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DesignDocDeleteReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, nil, err
	}
	switch value := result.(type) {
	case *DesignDocDeleteOK:
		return value, nil, nil
	case *DesignDocDeleteAccepted:
		return nil, value, nil
	}
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for design_documents: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  DesignDocExists returns the HTTP headers containing a minimal amount of information about the specified design document
*/
func (a *Client) DesignDocExists(params *DesignDocExistsParams) (*DesignDocExistsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDesignDocExistsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "designDocExists",
		Method:             "HEAD",
		PathPattern:        "/{db}/_design/{ddoc}",
		ProducesMediaTypes: []string{"application/json", "text/plain"},
		ConsumesMediaTypes: []string{"application/json", "text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DesignDocExistsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DesignDocExistsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for designDocExists: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  DesignDocGet returns the contents of the design document specified with the name of the design document and from the specified database from the URL

  Unless you request a specific revision, the latest revision of the document will always be returned.

*/
func (a *Client) DesignDocGet(params *DesignDocGetParams) (*DesignDocGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDesignDocGetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "designDocGet",
		Method:             "GET",
		PathPattern:        "/{db}/_design/{ddoc}",
		ProducesMediaTypes: []string{"application/json", "multipart/mixed", "multipart/related", "text/plain"},
		ConsumesMediaTypes: []string{"application/json", "multipart/mixed", "multipart/related", "text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DesignDocGetReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DesignDocGetOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for designDocGet: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  DesignDocInfo obtains information about the specified design document including the index index size and current status of the design document and associated index information
*/
func (a *Client) DesignDocInfo(params *DesignDocInfoParams) (*DesignDocInfoOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDesignDocInfoParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "designDocInfo",
		Method:             "HEAD",
		PathPattern:        "/{db}/_design/{ddoc}/_info",
		ProducesMediaTypes: []string{"application/json", "text/plain"},
		ConsumesMediaTypes: []string{"application/json", "text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DesignDocInfoReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DesignDocInfoOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for designDocInfo: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  DesignDocPut thes p u t method creates a new named design document or creates a new revision of the existing design document

  *Note*
that for filters, lists, shows and updates fields objects are mapping of function name to string function source code. For views mapping is the same except that values are objects with map and reduce (optional) keys which also contains functions source code.

*/
func (a *Client) DesignDocPut(params *DesignDocPutParams) (*DesignDocPutOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDesignDocPutParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "designDocPut",
		Method:             "PUT",
		PathPattern:        "/{db}/_design/{ddoc}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DesignDocPutReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DesignDocPutOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for designDocPut: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  DesignDocSearch executes a search request against the named index in the specified design document

  *Warning*
Search endpoints require a running search plugin connected to each cluster node. See Search Plugin Installation for details.

*Note*
You must enable faceting before you can use the counts, drilldown, and ranges parameters.

*Note*
Faceting and grouping are not supported on partitioned searches, so the following query parameters should not be used on those requests: counts, drilldown, ranges, and group_field, group_limit, group_sort``.

*Note*
Do not combine the bookmark and stale options. These options constrain the choice of shard replicas to use for the response. When used together, the options might cause problems when contact is attempted with replicas that are slow or not available.

*/
func (a *Client) DesignDocSearch(params *DesignDocSearchParams) (*DesignDocSearchOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDesignDocSearchParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "designDocSearch",
		Method:             "GET",
		PathPattern:        "/{db}/_design/{ddoc}/_search/{index}",
		ProducesMediaTypes: []string{"application/json", "text/plain"},
		ConsumesMediaTypes: []string{"application/json", "text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DesignDocSearchReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DesignDocSearchOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for designDocSearch: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  DesignDocSearchInfo executes a search request against the named index in the specified design document

  *Warning*
Search endpoints require a running search plugin connected to each cluster node. See Search Plugin Installation for details.

*/
func (a *Client) DesignDocSearchInfo(params *DesignDocSearchInfoParams) (*DesignDocSearchInfoOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDesignDocSearchInfoParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "designDocSearchInfo",
		Method:             "GET",
		PathPattern:        "/{db}/_design/{ddoc}/_search_info/{index}",
		ProducesMediaTypes: []string{"application/json", "text/plain"},
		ConsumesMediaTypes: []string{"application/json", "text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DesignDocSearchInfoReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DesignDocSearchInfoOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for designDocSearchInfo: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  DesignDocView executes the specified view function from the specified design document
*/
func (a *Client) DesignDocView(params *DesignDocViewParams) (*DesignDocViewOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDesignDocViewParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "designDocView",
		Method:             "GET",
		PathPattern:        "/{db}/_design/{ddoc}/_view/{view}",
		ProducesMediaTypes: []string{"application/json", "text/plain"},
		ConsumesMediaTypes: []string{"application/json", "text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DesignDocViewReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DesignDocViewOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for designDocView: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  DesignDocViewPost executes the specified view function from the specified design document

  POST view functionality supports identical parameters and behavior as specified in the GET /{db}/_design/{ddoc}/_view/{view} API but allows for the query string parameters to be supplied as keys in a JSON object in the body of the POST request.

*/
func (a *Client) DesignDocViewPost(params *DesignDocViewPostParams) (*DesignDocViewPostOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDesignDocViewPostParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "designDocViewPost",
		Method:             "POST",
		PathPattern:        "/{db}/_design/{ddoc}/_view/{view}",
		ProducesMediaTypes: []string{"application/json", "text/plain"},
		ConsumesMediaTypes: []string{"application/json", "text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DesignDocViewPostReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DesignDocViewPostOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for designDocViewPost: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
