// Code generated by go-swagger; DO NOT EDIT.

package design_documents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rossmerr/couchdb_go/models"
)

// DesignDocSearchInfoReader is a Reader for the DesignDocSearchInfo structure.
type DesignDocSearchInfoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DesignDocSearchInfoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDesignDocSearchInfoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDesignDocSearchInfoBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDesignDocSearchInfoUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDesignDocSearchInfoNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDesignDocSearchInfoOK creates a DesignDocSearchInfoOK with default headers values
func NewDesignDocSearchInfoOK() *DesignDocSearchInfoOK {
	return &DesignDocSearchInfoOK{}
}

/* DesignDocSearchInfoOK describes a response with status code 200, with default header values.

Request completed successfully
*/
type DesignDocSearchInfoOK struct {

	/* Response signature
	 */
	ETag string

	/* chunked
	 */
	TransferEncoding string

	Payload *models.InlineResponse2007
}

func (o *DesignDocSearchInfoOK) Error() string {
	return fmt.Sprintf("[GET /{db}/_design/{ddoc}/_search_info/{index}][%d] designDocSearchInfoOK  %+v", 200, o.Payload)
}
func (o *DesignDocSearchInfoOK) GetPayload() *models.InlineResponse2007 {
	return o.Payload
}

func (o *DesignDocSearchInfoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header ETag
	hdrETag := response.GetHeader("ETag")

	if hdrETag != "" {
		o.ETag = hdrETag
	}

	// hydrates response header Transfer-Encoding
	hdrTransferEncoding := response.GetHeader("Transfer-Encoding")

	if hdrTransferEncoding != "" {
		o.TransferEncoding = hdrTransferEncoding
	}

	o.Payload = new(models.InlineResponse2007)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDesignDocSearchInfoBadRequest creates a DesignDocSearchInfoBadRequest with default headers values
func NewDesignDocSearchInfoBadRequest() *DesignDocSearchInfoBadRequest {
	return &DesignDocSearchInfoBadRequest{}
}

/* DesignDocSearchInfoBadRequest describes a response with status code 400, with default header values.

Invalid request
*/
type DesignDocSearchInfoBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *DesignDocSearchInfoBadRequest) Error() string {
	return fmt.Sprintf("[GET /{db}/_design/{ddoc}/_search_info/{index}][%d] designDocSearchInfoBadRequest  %+v", 400, o.Payload)
}
func (o *DesignDocSearchInfoBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DesignDocSearchInfoBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDesignDocSearchInfoUnauthorized creates a DesignDocSearchInfoUnauthorized with default headers values
func NewDesignDocSearchInfoUnauthorized() *DesignDocSearchInfoUnauthorized {
	return &DesignDocSearchInfoUnauthorized{}
}

/* DesignDocSearchInfoUnauthorized describes a response with status code 401, with default header values.

Read permission required
*/
type DesignDocSearchInfoUnauthorized struct {
	Payload *models.ErrorResponse
}

func (o *DesignDocSearchInfoUnauthorized) Error() string {
	return fmt.Sprintf("[GET /{db}/_design/{ddoc}/_search_info/{index}][%d] designDocSearchInfoUnauthorized  %+v", 401, o.Payload)
}
func (o *DesignDocSearchInfoUnauthorized) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DesignDocSearchInfoUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDesignDocSearchInfoNotFound creates a DesignDocSearchInfoNotFound with default headers values
func NewDesignDocSearchInfoNotFound() *DesignDocSearchInfoNotFound {
	return &DesignDocSearchInfoNotFound{}
}

/* DesignDocSearchInfoNotFound describes a response with status code 404, with default header values.

Specified database, design document or view is missed
*/
type DesignDocSearchInfoNotFound struct {
	Payload *models.ErrorResponse
}

func (o *DesignDocSearchInfoNotFound) Error() string {
	return fmt.Sprintf("[GET /{db}/_design/{ddoc}/_search_info/{index}][%d] designDocSearchInfoNotFound  %+v", 404, o.Payload)
}
func (o *DesignDocSearchInfoNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DesignDocSearchInfoNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
