// Code generated by go-swagger; DO NOT EDIT.

package partition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/RossMerr/couchdb_go/models"
)

// PartitionDocGetReader is a Reader for the PartitionDocGet structure.
type PartitionDocGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PartitionDocGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPartitionDocGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPartitionDocGetOK creates a PartitionDocGetOK with default headers values
func NewPartitionDocGetOK() *PartitionDocGetOK {
	return &PartitionDocGetOK{}
}

/*PartitionDocGetOK handles this case with default header values.

Request completed successfully
*/
type PartitionDocGetOK struct {
	Payload *models.Partition
}

func (o *PartitionDocGetOK) Error() string {
	return fmt.Sprintf("[GET /{db}/_partition/{partition}][%d] partitionDocGetOK  %+v", 200, o.Payload)
}

func (o *PartitionDocGetOK) GetPayload() *models.Partition {
	return o.Payload
}

func (o *PartitionDocGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Partition)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
