// Code generated by go-swagger; DO NOT EDIT.

package partition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rossmerr/couchdb_go/models"
)

// PartitionDocGetAllReader is a Reader for the PartitionDocGetAll structure.
type PartitionDocGetAllReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PartitionDocGetAllReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPartitionDocGetAllOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewPartitionDocGetAllNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPartitionDocGetAllOK creates a PartitionDocGetAllOK with default headers values
func NewPartitionDocGetAllOK() *PartitionDocGetAllOK {
	return &PartitionDocGetAllOK{}
}

/*PartitionDocGetAllOK handles this case with default header values.

Request completed successfully
*/
type PartitionDocGetAllOK struct {
	Payload *models.Pagination
}

func (o *PartitionDocGetAllOK) Error() string {
	return fmt.Sprintf("[GET /{db}/_partition/{partition}/_all_docs][%d] partitionDocGetAllOK  %+v", 200, o.Payload)
}

func (o *PartitionDocGetAllOK) GetPayload() *models.Pagination {
	return o.Payload
}

func (o *PartitionDocGetAllOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Pagination)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPartitionDocGetAllNotFound creates a PartitionDocGetAllNotFound with default headers values
func NewPartitionDocGetAllNotFound() *PartitionDocGetAllNotFound {
	return &PartitionDocGetAllNotFound{}
}

/*PartitionDocGetAllNotFound handles this case with default header values.

Requested database not found
*/
type PartitionDocGetAllNotFound struct {
	Payload *models.ErrorResponse
}

func (o *PartitionDocGetAllNotFound) Error() string {
	return fmt.Sprintf("[GET /{db}/_partition/{partition}/_all_docs][%d] partitionDocGetAllNotFound  %+v", 404, o.Payload)
}

func (o *PartitionDocGetAllNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PartitionDocGetAllNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
