// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Body4 body 4
//
// swagger:model body_4
type Body4 struct {

	// docs
	Docs []*Keys `json:"docs"`
}

// Validate validates this body 4
func (m *Body4) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDocs(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Body4) validateDocs(formats strfmt.Registry) error {
	if swag.IsZero(m.Docs) { // not required
		return nil
	}

	for i := 0; i < len(m.Docs); i++ {
		if swag.IsZero(m.Docs[i]) { // not required
			continue
		}

		if m.Docs[i] != nil {
			if err := m.Docs[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("docs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this body 4 based on the context it is used
func (m *Body4) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDocs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Body4) contextValidateDocs(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Docs); i++ {

		if m.Docs[i] != nil {
			if err := m.Docs[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("docs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Body4) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Body4) UnmarshalBinary(b []byte) error {
	var res Body4
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
