// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BulkResponse bulk response
//
// swagger:model BulkResponse
type BulkResponse struct {
	DocumentOK

	ErrorResponse
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *BulkResponse) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 DocumentOK
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.DocumentOK = aO0

	// AO1
	var aO1 ErrorResponse
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.ErrorResponse = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m BulkResponse) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.DocumentOK)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.ErrorResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this bulk response
func (m *BulkResponse) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with DocumentOK
	if err := m.DocumentOK.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with ErrorResponse
	if err := m.ErrorResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *BulkResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BulkResponse) UnmarshalBinary(b []byte) error {
	var res BulkResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
