// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DatabaseCluster database cluster
//
// swagger:model Database_cluster
type DatabaseCluster struct {

	// Replicas. The number of copies of every document.
	N int64 `json:"n,omitempty"`

	// Shards. The number of range partitions.
	Q int64 `json:"q,omitempty"`

	// Read quorum. The number of consistent copies of a document that need to be read before a successful reply.
	R int64 `json:"r,omitempty"`

	// Write quorum. The number of copies of a document that need to be written before a successful reply.
	W int64 `json:"w,omitempty"`
}

// Validate validates this database cluster
func (m *DatabaseCluster) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this database cluster based on context it is used
func (m *DatabaseCluster) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DatabaseCluster) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DatabaseCluster) UnmarshalBinary(b []byte) error {
	var res DatabaseCluster
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
