// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DocumentOK document o k
//
// swagger:model DocumentOK
type DocumentOK struct {

	// Document ID
	ID string `json:"id,omitempty"`

	// Operation status
	Ok bool `json:"ok,omitempty"`

	// Revision MVCC token
	Rev string `json:"rev,omitempty"`
}

// Validate validates this document o k
func (m *DocumentOK) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DocumentOK) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DocumentOK) UnmarshalBinary(b []byte) error {
	var res DocumentOK
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
