// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InlineResponse2005 inline response 200 5
//
// swagger:model inline_response_200_5
type InlineResponse2005 struct {

	// admins
	Admins *Admins `json:"admins,omitempty"`

	// members
	Members *Members `json:"members,omitempty"`
}

// Validate validates this inline response 200 5
func (m *InlineResponse2005) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAdmins(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMembers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InlineResponse2005) validateAdmins(formats strfmt.Registry) error {
	if swag.IsZero(m.Admins) { // not required
		return nil
	}

	if m.Admins != nil {
		if err := m.Admins.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("admins")
			}
			return err
		}
	}

	return nil
}

func (m *InlineResponse2005) validateMembers(formats strfmt.Registry) error {
	if swag.IsZero(m.Members) { // not required
		return nil
	}

	if m.Members != nil {
		if err := m.Members.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("members")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this inline response 200 5 based on the context it is used
func (m *InlineResponse2005) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAdmins(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMembers(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InlineResponse2005) contextValidateAdmins(ctx context.Context, formats strfmt.Registry) error {

	if m.Admins != nil {
		if err := m.Admins.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("admins")
			}
			return err
		}
	}

	return nil
}

func (m *InlineResponse2005) contextValidateMembers(ctx context.Context, formats strfmt.Registry) error {

	if m.Members != nil {
		if err := m.Members.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("members")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InlineResponse2005) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InlineResponse2005) UnmarshalBinary(b []byte) error {
	var res InlineResponse2005
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
