// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Members they can read all types of documents from the DB, and they can write (and edit) documents to the DB except for design documents.
//
// swagger:model Members
type Members struct {

	// List of CouchDB user names
	Name []string `json:"name"`

	// List of users roles
	Roles []string `json:"roles"`
}

// Validate validates this members
func (m *Members) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Members) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Members) UnmarshalBinary(b []byte) error {
	var res Members
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
