// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ViewIndexSizes view index sizes
//
// swagger:model ViewIndex_sizes
type ViewIndexSizes struct {

	// The size of live data inside the view, in bytes
	Active int64 `json:"active,omitempty"`

	// Size in bytes of the view as stored on disk
	Disk int64 `json:"disk,omitempty"`

	// The uncompressed size of view contents in bytes
	External int64 `json:"external,omitempty"`
}

// Validate validates this view index sizes
func (m *ViewIndexSizes) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this view index sizes based on context it is used
func (m *ViewIndexSizes) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ViewIndexSizes) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ViewIndexSizes) UnmarshalBinary(b []byte) error {
	var res ViewIndexSizes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
